import {
  gift10Img,
  gift10WebpImg,
  gift1Img,
  gift1WebpImg,
  gift2Img,
  gift2WebpImg,
  gift3Img,
  gift3WebpImg,
  gift4Img,
  gift4WebpImg,
  gift5Img,
  gift5WebpImg,
  gift6Img,
  gift6WebpImg,
  gift7Img,
  gift7WebpImg,
  gift8Img,
  gift8WebpImg,
  gift9Img,
  gift9WebpImg,
} from "@/assets/images";

export const GIFTS = [
  {
    id: 1,
    chance: 5,
    image: gift1Img,
    imageWebp: gift1WebpImg,
    stars: 10,
  },
  {
    id: 2,
    chance: 10,
    image: gift2Img,
    imageWebp: gift2WebpImg,
    stars: 20,
  },
  {
    id: 3,
    chance: 12,
    image: gift3Img,
    imageWebp: gift3WebpImg,
    stars: 30,
  },
  {
    id: 4,
    chance: 13,
    image: gift4Img,
    imageWebp: gift4WebpImg,
    stars: 40,
  },
  {
    id: 5,
    chance: 15,
    image: gift5Img,
    imageWebp: gift5WebpImg,
    stars: 50,
  },
  {
    id: 6,
    chance: 13,
    image: gift6Img,
    imageWebp: gift6WebpImg,
    stars: 60,
  },
  {
    id: 7,
    chance: 12,
    image: gift7Img,
    imageWebp: gift7WebpImg,
    stars: 70,
  },
  {
    id: 8,
    chance: 10,
    image: gift8Img,
    imageWebp: gift8WebpImg,
    stars: 80,
  },
  {
    id: 9,
    chance: 6,
    image: gift9Img,
    imageWebp: gift9WebpImg,
    stars: 90,
  },
  {
    id: 10,
    chance: 4,
    image: gift10Img,
    imageWebp: gift10WebpImg,
    stars: 100,
  },
];
